class HueyException(Exception): ...
class RateLimitExceeded(HueyException): ...
class ResultTimeout(HueyException): ...
class TaskException(HueyException): ...
class TaskLockedException(TaskException): ...
