---
chart_key: implied_daily_growth_rate
data_source: growth_rates # SQL table
title: Implied daily growth rate
mqtt_topic: growth_rate_calculating/growth_rate
source: app
payload_key: growth_rate
y_axis_label: Growth rate, d⁻¹
interpolation: stepAfter
y_axis_domain: [-0.1, 1.0]
y_transformation: "(y) => 24 * y"
lookback: 100000
fixed_decimals: 2
down_sample: true
