---
chart_key: optical_density
data_source: od_readings # SQL table
title: Optical density
mqtt_topic: [od_reading/od1, od_reading/od2]
source: app
payload_key: od
y_axis_label: Reading
interpolation: stepAfter
lookback: parseFloat(config['ui.overview.settings']['raw_od_lookback_hours'])
fixed_decimals: 3
y_axis_domain: [0.001, 0.05] # good default for near 0 OD, but will break out after growth.
down_sample: true
