---
display_name: LED automation
job_name: led_automation
subtext: automation_name
source: app
display: true
description:  Start an LED automation to control the LEDs (for example, in a photo-bioreactor).
published_settings:
  - key: automation_name
    type: string
    display: false
