---
chart_key: normalized_optical_density
data_source: od_readings_filtered # SQL table
title: Normalized optical density
mqtt_topic: growth_rate_calculating/od_filtered
source: app
payload_key: od_filtered
y_axis_label: Current OD / initial OD
interpolation: stepAfter
y_axis_domain: [0.98, 1.02]
lookback: parseFloat(config['ui.overview.settings']['filtered_od_lookback_hours'])
fixed_decimals: 2
down_sample: true
