---
chart_key: raw_optical_density
data_source: raw_od_readings # SQL table
title: Raw optical density (uncalibrated)
mqtt_topic: [od_reading/raw_od1, od_reading/raw_od2]
source: app
payload_key: od
y_axis_label: Reading
interpolation: stepAfter
lookback: parseFloat(config['ui.overview.settings']['raw_od_lookback_hours'])
fixed_decimals: 3
y_axis_domain: [0.001, 0.05] # good default for near 0 OD, but will break out after growth.
down_sample: true
