from collections.abc import Callable
from typing import Any
from typing import Protocol

SET_PULL_DOWN: int
SET_PULL_UP: int
BOTH_EDGES: int
FALLING_EDGE: int

class error(Exception): ...

class _Callback(Protocol):
    def cancel(self) -> None: ...

def gpiochip_open(gpiochip: int) -> Any: ...
def gpiochip_close(handle: Any) -> None: ...
def gpio_claim_output(handle: Any, gpio: Any, level: int = ...) -> None: ...
def gpio_claim_input(handle: Any, gpio: Any, lFlags: int = ...) -> None: ...
def gpio_claim_alert(handle: Any, gpio: Any, eFlags: int, lFlags: int = ...) -> None: ...
def gpio_write(handle: Any, gpio: Any, level: int) -> None: ...
def tx_pwm(handle: Any, gpio: Any, pwm_frequency: float, pwm_duty_cycle: float) -> None: ...
def callback(
    handle: Any,
    gpio: Any,
    edge: int,
    func: Callable[[int, int, int, int], None] | None = ...,
) -> _Callback: ...
