from typing import Any

def clf() -> None: ...
def plot(*args: Any, **kwargs: Any) -> None: ...
def scatter(*args: Any, **kwargs: Any) -> None: ...
def plot_size(width: int, height: int) -> None: ...
def theme(name: str) -> None: ...
def title(label: str) -> None: ...
def xlabel(label: str) -> None: ...
def ylabel(label: str) -> None: ...
def xlim(left: float | None, right: float | None) -> None: ...
def yfrequency(value: int) -> None: ...
def xfrequency(value: int) -> None: ...
def show() -> None: ...
