# -*- coding: utf-8 -*-
from __future__ import annotations


NO_NETWORK_CONNECTION = 1
MQTT_CLIENT_NOT_CONNECTED_TO_LEADER = 2
DISK_IS_ALMOST_FULL = 3
STIRRING_FAILED = 4
ADC_INPUT_TOO_HIGH = 5
PCB_TEMPERATURE_TOO_HIGH = 6
VOLTAGE_PROBLEM = 7
WEBSERVER_OFFLINE = 8
