# See documentation for this file at https://docs.pioreactor.com/user-guide/configuration

[PWM]
# map the PWM channels to externals.
# hardware PWM are available on channels 2 & 4.
1=stirring
2=media
3=alt_media
4=waste
5=heating

[leds]
# Specify LED channels, add LED labels in the UI, and access specific LEDs programmatically. Ex: A=IR, B=white1, C=white2. Should be unique names.
# To measure optical density, one LED channel should be labelled `IR`.
A=IR
B=
C=
D=

[stirring.config]
initial_target_rpm=500
initial_duty_cycle=30
pwm_hz=200
use_rpm=1
duration_between_updates_seconds=23
# config below are for "dodging" behaviour - change stirring behaviour during an OD reading snapshot.
enable_dodging_od=False
post_delay_duration=0.25
pre_delay_duration=1.5
target_rpm_during_od_reading=0
target_rpm_outside_od_reading=500

[od_reading.config]
# how many optical density measurements should be published per second? Recommended maximum is 1.
samples_per_second=0.2

# default intensity of IR LED. The value `auto` will automatically choose an IR LED intensity that matches an internal value.
# Or set an integer between 0 and 100. Higher is usually better (>= 50), but keep less than 90 for longevity.
ir_led_intensity=80

# lower to remove heating artifacts, but may introduce more noise in the OD. Must be between 0 and 1.
pd_reference_ema=0.75

# populate with your local AC frequency (typically 50 or 60) to get slightly reduced noise. Inferred from data otherwise.
# local_ac_hz=

# apply a smoothing penalizer
smoothing_penalizer=3.0

# turn off the other LED channels during an OD reading snapshot.
turn_off_leds_during_reading=1

# in seconds
duration_between_led_off_and_od_reading=0.125

# when od reading starts, read the baseline signal with the IR LED off, and subtract this from future readings: a dark offset.
use_dark_offsets=True

# choose the method to normalize signals using REF. {unity,classic}
ref_normalization=unity

[od_config.photodiode_channel]
# Default IR photodiode channel(s) to use and its angle relative to the IR LED(s),
# OR choose the reference photodiode using the keyword REF.
# Only valid angles are {45, 90, 135, 180}
# Only allowable channels are {1, 2, 3, 4}
1=REF
2=90
3=
4=

[bioreactor]
# used in dosing automations
# efflux_tube_volume_ml is determined by the volume that just touches the outflow tube. I.e. if you
# where to keep running the waste pump, what would the stable volume be. This can be changed in the UI.
# see docs: https://docs.pioreactor.com/user-guide/prepare-vial-for-cultures#extra
efflux_tube_volume_ml=15
initial_volume_ml=15
initial_alt_media_fraction=0


[dosing_automation.config]
pause_between_subdoses_seconds=5
waste_removal_multiplier=2
max_subdose=1.0


[dosing_automation.pid_morbidostat]
Kp=1
Ki=0
Kd=0
minimum_dosing_volume_ml=0.1

[temperature_automation.thermostat]
Kp=2.6
Ki=0.0
Kd=4.6

[stirring.pid]
Kp=0.005
Ki=0.0
Kd=0.0


[growth_rate_calculating.config]
# these next two parameters control the length and magnitude
# of the variance shift that our Kalman filter performs after a dosing event
ekf_outlier_std_threshold=5.0
samples_for_od_statistics=10

[dosing_automation.turbidostat]
# one of {od,fused_od,normalized_od,auto}
biomass_signal=auto

[storage]
database=/home/pioreactor/.pioreactor/storage/pioreactor.sqlite
temporary_cache=/run/pioreactor/cache/local_intermittent_pioreactor_metadata.sqlite
persistent_cache=/home/pioreactor/.pioreactor/storage/local_persistent_pioreactor_metadata.sqlite


# in a cluster, leader will backup the db to workers. Set the number of workers below.
number_of_backup_replicates_to_workers=2

[logging]
# where, on each Rpi, to store the logs
log_file=/var/log/pioreactor.log
ui_log_file=/var/log/pioreactor.log

# See Python's logging module for possible values
# logs also appear in the UI
ui_log_level=INFO
console_log_level=DEBUG

[cluster.topology]
# should be a hostname defined on the network
# See docs: https://docs.pioreactor.com/user-guide/create-cluster
leader_hostname=

# something like: leadername.local or a static IPv4 address
leader_address=

[cluster.addresses]
# You can add static IPv4 addresses here for other Pioreactors in the cluster. This will bypass mDNS. Example:
# pio01=10.42.0.1
# pio02=10.42.0.3
# The leader's address is automatically added.
# If addresses aren't present, mDNS will be used -> query for <hostname>.local on the network.


[mqtt]
username=pioreactor
password=raspberry
broker_address=
broker_ws_port=9001
broker_port=1883
ws_protocol=ws
use_tls=0

[ui]
# the UI will be available at the below alias, along with <leader_hostname>.local
# note - it must end in .local, and subdomains are not allowed.
# requires a reboot after changing.
domain_alias=pioreactor.local
# port the webserver is listening to, found in lighttpd.conf
port=80
# protocol the webserver expects.
proto=http

[ui.overview.settings]
# only display the previous X hours of data.
# lookback_hours can be decimal values, too. Ex: 0.5 to represent 30 minutes.
filtered_od_lookback_hours=50000
raw_od_lookback_hours=50000
# to change the default x-axis: clock_time or hours
time_display_mode=clock_time


[ui.overview.charts]
# show/hide charts on the PioreactorUI dashboard
# 1 is show, 0 is hide
optical_density=1
normalized_optical_density=1
implied_growth_rate=1
implied_daily_growth_rate=0
raw_optical_density=0
temperature=1
current_volume_ml=0
fused_optical_density=0
fraction_of_volume_that_is_alternative_media=0

[ui.overview.cards]
# show/hide cards on the PioreactorUI dashboard
# 1 is show, 0 is hide
dosings=1
event_logs=1
profiles=1

[local_access_point]
# Only used if using the a pioreactor as a access point.
# See details at https://docs.pioreactor.com/user-guide/local-access-point
ssid=pioreactor
passphrase=raspberry
proto=rsn
