name: CI Web

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python libraries
        run: |
          pip install -r ../requirements/requirements_dev.txt
          pip install -e ../core
          pip install pyyaml
          pip list

      - name: Mosquitto MQTT Broker in GitHub Actions
        uses: Namoshek/mosquitto-github-action@v1
        with:
          version: '1.6'

      - name: Create pioreactor folders and env
        run: |
          mkdir -p .pioreactor/storage
          mkdir -p /tmp/pioreactor_cache/
          mv .env.example .env

      - name: Run tests
        run: |
          pytest web/tests/ -vv --timeout 600 --random-order --durations 15
        env:
          TESTING: 1
          TMPDIR: /tmp/
